[licenses]
version = 2
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "Unicode-3.0",
  "Zlib",
  "MPL-2.0",
  "BSD-3-Clause",
  "CDLA-Permissive-2.0",
  "ISC",
]

[licenses.private]
ignore = false

[advisories]
yanked = "deny"
ignore = [
  "RUSTSEC-2024-0436",
  "RUSTSEC-2024-0320",
] # paste, yaml_rust unmaintained crates
version = 2

[bans]
multiple-versions = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
