name: CI

on:
  push:
    branches: [main]
    paths:
      - '**/*.rs'
      - '**/*.toml'
      - 'Cargo.lock'

  pull_request:
    branches: [main]
    paths:
      - '**/*.rs'
      - '**/*.toml'
      - 'Cargo.lock'

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@v2
        with:
          log-level: warn
          command: check
          arguments: --all-features

      - name: Install Taplo CLI
        run: cargo install taplo-cli --locked

      - name: Run CI checks
        run: cargo xtask ci
