name: Shell Format Check
on:
  push:
    branches: [ main ]
    paths:
      - '**/*.sh'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.sh'
  workflow_dispatch:

jobs:
  shell-format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install shfmt
      run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

    - name: Check formatting
      run: |
        find . -name "*.sh" -o -name "*.bash" | \
        grep -v "./scripts/modules/Browser/Extensions.sh" | \
        xargs shfmt -i 4 -ci -sr -kp -d
